DROP DATABASE empleadosnm;
CREATE DATABASE empleadosnm;

USE empleadosnm;

CREATE TABLE DPTO(
	COD_DPTO VARCHAR(4),
	NOMBRE VARCHAR(50)
)ENGINE=InnoDB;

CREATE TABLE EMPLE(
	DNI VARCHAR(9),
	NOMBRE VARCHAR(50),
	SALARIO DOUBLE,
	FECHA_NAC DATE
)ENGINE=InnoDB;

CREATE TABLE EMPLE_DPTO(
	COD_DPTO VARCHAR(4),
	DNI VARCHAR(9),
	FECHA_INICIO DATE,
	FECHA_FIN DATE
)ENGINE=InnoDB;


/* ALTER TABLE */

ALTER TABLE DPTO ADD CONSTRAINT PK_DPTO PRIMARY KEY (COD_DPTO);
ALTER TABLE EMPLE ADD CONSTRAINT PK_EMPLE PRIMARY KEY (DNI);s

ALTER TABLE EMPLE_DPTO ADD CONSTRAINT PK_EMPLE_DPTO PRIMARY KEY (COD_DPTO,DNI,FECHA_INICIO);

ALTER TABLE EMPLE_DPTO ADD CONSTRAINT FK_EMPLE_DPTO_COD FOREIGN KEY (COD_DPTO) REFERENCES DPTO(COD_DPTO);
ALTER TABLE EMPLE_DPTO ADD CONSTRAINT FK_EMPLE_DPTO_DNI FOREIGN KEY (DNI) REFERENCES EMPLE(DNI);

/* INSERTS */

/*DPTO*/
INSERT INTO DPTO(COD_DPTO,NOMBRE) VALUES ('D001','CONTABILIDAD');
INSERT INTO DPTO(COD_DPTO,NOMBRE) VALUES ('D002','NOMINAS');
INSERT INTO DPTO(COD_DPTO,NOMBRE) VALUES ('D003','FINANZAS');
INSERT INTO DPTO(COD_DPTO,NOMBRE) VALUES ('D004','VENTAS');

/*EMPLE*/
INSERT INTO EMPLE (DNI,NOMBRE,SALARIO,FECHA_NAC)
VALUES('11111111A','ANA','2000','2000-01-01');

INSERT INTO EMPLE (DNI,NOMBRE,SALARIO,FECHA_NAC)
VALUES('22222222B','JUAN','4000','1970-04-15');

INSERT INTO EMPLE (DNI,NOMBRE,SALARIO,FECHA_NAC)
VALUES('33333333C','ALBERTO','2500','2004-02-06');


INSERT INTO EMPLE (DNI,NOMBRE,SALARIO,FECHA_NAC)
VALUES('44444444C','GUILLE','5000','2003-12-21');

INSERT INTO EMPLE (DNI,NOMBRE,SALARIO,FECHA_NAC)
VALUES('00000000X','PRUEBA','10','2003-12-21');

/*EMPLE_DPTO*/
INSERT INTO EMPLE_DPTO (COD_DPTO,DNI,FECHA_INICIO,FECHA_FIN)
VALUES ('D001','11111111A','2020-1-1',NULL);

INSERT INTO EMPLE_DPTO (COD_DPTO,DNI,FECHA_INICIO,FECHA_FIN)
VALUES ('D002','22222222B','2020-1-1',NULL);

INSERT INTO EMPLE_DPTO (COD_DPTO,DNI,FECHA_INICIO,FECHA_FIN)
VALUES ('D003','33333333C','2020-1-1',NULL);